version: "3"
services:
  tomcat:
    image: tomcat:9.0.50-jdk8-openjdk-slim-buster
    ports:
    - 8080:8080
    volumes:
    - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ./webapps:/usr/local/tomcat/webapps